name: CI/CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Dart Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.dart_tool/cache
          key: ${{ runner.os }}-dart-dependencies-${{ HashFiles() }}
          restore-keys: |
            ${{ runner.os }}-dart-dependencies-
      - name: Build
        run: flutter build

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'build' # DEPLOYMENT_URL: https://example.com
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Dart Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.dart_tool/cache
          key: ${{ runner.os }}-dart-dependencies-${{ HashFiles() }}
          restore-keys: |
            ${{ runner.os }}-dart-dependencies-
      - name: Deploy
        run: # Deployment commands here